name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
    
    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
    
    - name: Code Quality
      run: |
        poetry run black --check . || echo "::warning file=black::Code style issues found"

    - name: Lint
      run: |
        poetry run flake8 pms tests || echo "::warning file=flake8::Lint issues found"

    - name: Type Check
      run: |
        poetry run mypy pms tests || echo "::warning file=mypy::Type check issues found"

    - name: Run Tests
      run: |
        poetry run pytest --cov=pms --cov-report=xml
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    
    